import { z } from 'zod';
import {
  LIFECYCLE_STATES,
  MEMORY_KINDS,
  MEMORY_TYPES,
  SOURCE_KINDS,
  VERIFIED_WITH,
  type MemoryFrontmatter,
} from './types.js';

const isoOrNever = z.string().refine(
  (s) => s === 'never' || !isNaN(Date.parse(s)),
  'Must be ISO 8601 date or "never"',
);

const codeAnchorSchema = z.object({
  file: z.string().describe('Path relative to the project root (POSIX separators).'),
  sha: z.string().describe('Git blob SHA of the file content at anchor time (as computed by `git hash-object`).'),
  repo: z.string().optional().describe('When set, `file` lives in another repo checked out next to this project (or under a configured search path).'),
});

/**
 * v0.3 frontmatter schema. The reader normalizes legacy field/state names
 * (decay_after, corrects/corrected_by, correction_reason, captured/corrected/decayed/archived,
 * top-level confidence, ext.code_anchors) into this shape before validation.
 *
 * Field-level `.describe()` calls are the source of truth for `SCHEMA.md`
 * (generated by `scripts/generate-schema.ts`). Keep descriptions to one
 * sentence each; mirror wording from `types.ts` and `SPEC.md §6.2`.
 */
export const memoryFrontmatterSchema = z.object({
  id: z.string().regex(/^ms_[A-Z0-9]{26}$/, 'ID must be ms_ followed by a 26-char ULID')
    .describe('ULID prefixed with `ms_`; globally unique within the store and chronologically sortable.'),
  kind: z.enum(MEMORY_KINDS).default('claim')
    .describe('`claim` for fact/decision/procedure memories; `observation` for point-in-time notes that index a moment and expire rather than going stale.'),
  type: z.enum(MEMORY_TYPES).optional()
    .describe('Classification for claims (`fact` | `decision` | `procedure`); required when `kind: claim`, omitted on observations.'),
  state: z.enum(LIFECYCLE_STATES)
    .describe('Lifecycle state: `active` (current), `superseded` (replaced by another record), or `retired` (no longer relevant).'),
  created: z.string().refine(
    (s) => !isNaN(Date.parse(s)),
    'Must be a valid ISO 8601 date',
  ).describe('ISO 8601 timestamp when this record was first written.'),
  source: z.string().min(1)
    .describe('Who wrote the record (agent name, human identifier, or import label); required at write time, `"unknown"` is rejected.'),
  source_kind: z.enum(SOURCE_KINDS).optional()
    .describe('Trust tier inferred from `source` at write time: `operator` (human), `agent`, or `import`.'),
  tags: z.array(z.string()).default([])
    .describe('Free-form tag list for filtering and search.'),
  check_by: isoOrNever
    .describe('ISO 8601 deadline or `"never"`; when it passes the record is flagged `stale: true` at read time but never deleted (renamed from `decay_after`).'),
  stale: z.boolean().optional()
    .describe('Set when `check_by` has passed; cleared by a successful `verify`. Lazy-flagged in memory on read; physical removal only via `memspec sweep`.'),
  last_verified: z.string().refine(
    (s) => !isNaN(Date.parse(s)),
    'Must be a valid ISO 8601 date',
  ).optional().describe('ISO 8601 timestamp of the last successful verification; defaults to `created` when never verified.'),
  verified_with: z.enum(VERIFIED_WITH).optional()
    .describe('Witness class for the last verification, in descending strength: `anchor` > `operator` > `evidence` > `assertion`. Replaces the retired `confidence` field.'),
  pinned: z.boolean().optional()
    .describe('Operator-only flag; pinned claims are always surfaced in boot context (cap 5, ordered by `last_verified` descending).'),
  anchors: z.array(codeAnchorSchema).optional()
    .describe('Code anchors linking this memory to specific file contents; drift detected by comparing recorded SHA to current `git hash-object`. Promoted from `ext.code_anchors` to schema spine in v0.3.'),
  supersedes: z.array(z.string()).optional()
    .describe('Ids this record replaces (renamed from `corrects`; now an array to support N→1 merges).'),
  superseded_by: z.string().optional()
    .describe('Id of the record that replaced this one (renamed from `corrected_by`).'),
  supersede_reason: z.string().optional()
    .describe('Durable reason explaining why this record was superseded (renamed from `correction_reason`).'),
  conflicts_with: z.array(z.string()).optional()
    .describe('Explicit conflict edges to other memory ids; surfaced on read so contradictions are visible rather than blindly ranked.'),
  refines: z.array(z.string()).optional()
    .describe('Ids this record refines or elaborates on; the parent stays valid (v0.4 typed relation).'),
  supports: z.array(z.string()).optional()
    .describe('Ids this record provides evidence for (v0.4 typed relation).'),
  depends_on: z.array(z.string()).optional()
    .describe('Ids this record presupposes — a knowledge or chronological dependency (v0.4 typed relation).'),
  expires: z.string().refine(
    (s) => !isNaN(Date.parse(s)),
    'Must be a valid ISO 8601 date',
  ).optional().describe('Observations only: hard ISO 8601 expiry after which the record is no longer surfaced.'),
  ext: z.record(z.string(), z.unknown()).optional()
    .describe('Extension bag for non-schema fields (e.g. `ext.confirmations`, `ext.last_verification`, `ext.legacy_confidence`). Conventions documented in `src/lib/types.ts`.'),
}).refine(
  (data) => data.kind === 'observation' || data.type !== undefined,
  { message: 'Claims (kind: claim) require a type', path: ['type'] },
);

export type MemoryItemFrontmatter = z.infer<typeof memoryFrontmatterSchema>;

const LEGACY_STATE_MAP: Record<string, string> = {
  captured: 'active',
  corrected: 'superseded',
  decayed: 'retired',
  archived: 'retired',
};

/**
 * Map a legacy frontmatter object into v0.3 shape so the same validator
 * accepts pre-0.3 records. Mutates a clone, never the input.
 *
 * - state: captured → active, corrected → superseded, decayed|archived → retired
 * - decay_after → check_by
 * - corrects (string) → supersedes (array)
 * - corrected_by → superseded_by
 * - correction_reason → supersede_reason
 * - ext.code_anchors → top-level anchors (if anchors not already set)
 * - top-level confidence → ext.legacy_confidence (and removed from top level)
 */
export function normalizeLegacyFrontmatter(input: Record<string, unknown>): Record<string, unknown> {
  const data = { ...input };

  if (data.kind === undefined) data.kind = 'claim';

  if (typeof data.state === 'string' && data.state in LEGACY_STATE_MAP) {
    data.state = LEGACY_STATE_MAP[data.state];
  }

  if (data.check_by === undefined && data.decay_after !== undefined) {
    data.check_by = data.decay_after;
  }
  delete data.decay_after;

  if (data.supersedes === undefined && data.corrects !== undefined) {
    const raw = data.corrects;
    data.supersedes = Array.isArray(raw) ? raw : [raw];
  }
  delete data.corrects;

  if (data.superseded_by === undefined && data.corrected_by !== undefined) {
    data.superseded_by = data.corrected_by;
  }
  delete data.corrected_by;

  if (data.supersede_reason === undefined && data.correction_reason !== undefined) {
    data.supersede_reason = data.correction_reason;
  }
  delete data.correction_reason;

  const ext = (data.ext && typeof data.ext === 'object') ? { ...(data.ext as Record<string, unknown>) } : undefined;

  // Anchor promotion: ext.code_anchors → top-level anchors (if not already top-level).
  if (data.anchors === undefined && ext && Array.isArray(ext.code_anchors)) {
    data.anchors = ext.code_anchors;
  }

  // Confidence retirement: keep the historical value as ext.legacy_confidence; drop top-level.
  if (typeof data.confidence === 'number') {
    if (ext) {
      if (ext.legacy_confidence === undefined) ext.legacy_confidence = data.confidence;
    } else {
      data.ext = { legacy_confidence: data.confidence };
    }
  }
  delete data.confidence;

  if (ext !== undefined) data.ext = ext;

  return data;
}

export function validateFrontmatter(data: unknown): { success: true; data: MemoryItemFrontmatter } | { success: false; errors: string[] } {
  const normalized = data && typeof data === 'object'
    ? normalizeLegacyFrontmatter(data as Record<string, unknown>)
    : data;
  const result = memoryFrontmatterSchema.safeParse(normalized);
  if (result.success) {
    return { success: true, data: result.data };
  }
  return {
    success: false,
    errors: result.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`),
  };
}

export function assertValidFrontmatter(data: unknown): MemoryFrontmatter {
  const normalized = data && typeof data === 'object'
    ? normalizeLegacyFrontmatter(data as Record<string, unknown>)
    : data;
  return memoryFrontmatterSchema.parse(normalized) as MemoryFrontmatter;
}
